apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: localhost:32000/py-api:v8
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis.infra.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: "postgres.infra.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "usersdb"
            - name: POSTGRES_USER
              value: "usersvc"
            - name: POSTGRES_PASSWORD
              value: "usersvcpass"
---
apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: apps
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: python-api
